In [3]:
import pandas as pd
import csv

samsung_path = '005930_삼성전자.csv'
skhynix_path = '000660_SK하이닉스.csv'

samsung = pd.read_csv(samsung_path)
skhynix = pd.read_csv(skhynix_path)

df_samsung = pd.DataFrame(samsung)
df_skhynix = pd.DataFrame(skhynix)

print(df_samsung)
print(df_skhynix)

      code  name      date   open   high    low  close    volume  diffratio  \
0     5930  삼성전자  20150102  26800  26800  26540  26600   8774950   0.002261
1     5930  삼성전자  20150105  26720  26720  26260  26660  10139500   0.002256
2     5930  삼성전자  20150106  26300  26340  25760  25900  15235500  -0.028507
3     5930  삼성전자  20150107  25880  26220  25640  26140  14322750   0.009266
4     5930  삼성전자  20150108  26780  26780  26200  26280  14477600   0.005356
...    ...   ...       ...    ...    ...    ...    ...       ...        ...
2207  5930  삼성전자  20231221  74600  75000  74300  75000  13478766   0.002674
2208  5930  삼성전자  20231222  75800  76300  75400  75900  14515608   0.012000
2209  5930  삼성전자  20231226  76100  76700  75700  76600  13164909   0.009223
2210  5930  삼성전자  20231227  76700  78000  76500  78000  20651042   0.018277
2211  5930  삼성전자  20231228  77700  78500  77500  78500  17797536   0.006410

      high_close_ratio  ...     ma20         macd  macd_signal  minus_dmi  \
0             0.007519  ...  26253.0   485.535635   505.524982   0.222491
1             0.002251  ...  26288.0   468.387940   498.097574   0.278289
2             0.016988  ...  26283.0   388.991535   476.276366   0.346481
3             0.003060  ...  26288.0   341.497857   449.320664   0.324900
4             0.019026  ...  26283.0   311.563614   421.769254   0.271463
...                ...  ...      ...          ...          ...        ...
2207          0.000000  ...  72730.0   835.667626   692.181760   0.131505
2208          0.005270  ...  72940.0   973.336146   748.412637   0.108475
2209          0.001305  ...  73205.0  1125.916057   823.898964   0.093882
2210          0.000000  ...  73470.0  1344.321298   927.983430   0.076151
2211          0.000000  ...  73760.0  1540.000471  1050.386839   0.066491

      plus_dmi  rsi_signal           ubb  macd_signal_ratio  trans_price_mean  \
0     0.341876   75.396825  27373.697151          -0.039542          0.088855
1     0.292483   75.968992  27413.879305          -0.059646          0.088855
2     0.220549   34.285714  27415.135383          -0.183265          0.088855
3     0.186451   31.000000  27416.494106          -0.239969          0.088855
4     0.299697   37.623762  27410.663630          -0.261294          0.088855
...        ...         ...           ...                ...               ...
2207  0.359215   76.086957  74763.508764           0.207295          0.092304
2208  0.471435   78.431373  75356.957635           0.300534          0.092304
2209  0.461825   79.245283  75997.829164           0.366571          0.092331
2210  0.538285   93.333333  76975.844744           0.448648          0.092331
2211  0.533428   93.548387  77899.870326           0.466127          0.092331

      macd_signal_sign
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
...                ...
2207               NaN
2208               NaN
2209               NaN
2210               NaN
2211               NaN

[2212 rows x 92 columns]
      code    name      date    open    high     low   close   volume  \
0      660  SK하이닉스  20150102   47950   48400   47650   47750  1155944
1      660  SK하이닉스  20150105   48050   48400   47500   47650  1409146
2      660  SK하이닉스  20150106   47000   47600   46900   47500  1661196
3      660  SK하이닉스  20150107   46700   47600   46700   47400  1821266
4      660  SK하이닉스  20150108   48250   50000   47900   49950  5006675
...    ...     ...       ...     ...     ...     ...     ...      ...
2207   660  SK하이닉스  20231221  139200  140600  138100  140500  2737124
2208   660  SK하이닉스  20231222  142700  143700  140600  140600  3183709
2209   660  SK하이닉스  20231226  142000  142000  139400  140900  2239789
2210   660  SK하이닉스  20231227  140800  141600  139200  140400  2336777
2211   660  SK하이닉스  20231228  140900  141600  139500  141500  2459473

      diffratio  high_close_ratio  ...      ma20         macd  macd_signal  \
0      0.000000          0.013613  ...   47895.0    60.807176   111.387823
1     -0.002094          0.015740  ...   47875.0    49.890736    99.088406
2     -0.003148          0.002105  ...   47815.0    28.804189    85.031562
3     -0.002105          0.004219  ...   47767.5     3.978298    68.820909
4      0.053797          0.001001  ...   47832.5   187.892757    92.635279
...         ...               ...  ...       ...          ...          ...
2207   0.000000          0.000712  ...  132485.0  3045.828665  2022.705869
2208   0.000712          0.022048  ...  133115.0  3199.629437  2258.090583
2209   0.002134          0.007807  ...  133625.0  3307.356050  2467.692440
2210  -0.003549          0.008547  ...  134075.0  3314.379152  2637.029783
2211   0.007835          0.000707  ...  134630.0  3369.855569  2783.594940

      minus_dmi  plus_dmi  rsi_signal            ubb  macd_signal_ratio  \
0      0.163339  0.181204   59.813084   49376.073579          -0.454095
1      0.163728  0.160020   49.438202   49358.062266          -0.496503
2      0.228025  0.143850   36.842105   49253.968929          -0.661253
3      0.227313  0.126193   38.356164   49194.781184          -0.942193
4      0.161312  0.357570   73.148148   49523.116518           1.028307
...         ...       ...         ...            ...                ...
2207   0.166685  0.294332   89.156627  142789.270959           0.505819
2208   0.143540  0.387979   88.235294  143798.440211           0.416962
2209   0.180168  0.343291   86.666667  144786.187449           0.340263
2210   0.169586  0.305778   83.333333  145578.935253           0.256861
2211   0.152736  0.275394   75.531915  146453.989887           0.210613

      trans_price_mean  macd_signal_sign
0                  NaN               NaN
1                  NaN               NaN
2                  NaN               NaN
3                  NaN               NaN
4                  NaN               NaN
...                ...               ...
2207          0.083524               NaN
2208          0.083524               NaN
2209          0.083634               NaN
2210          0.083634               NaN
2211          0.083634               NaN

[2212 rows x 92 columns]

In [35]:
import numpy as np
import pandas as pd

# 2019-02-13 이후의 데이터만 필터링

# format date type
df_samsung['date'] = df_samsung['date'].astype('str')
df_samsung['date'] = pd.to_datetime(df_samsung['date'])
df_skhynix['date'] = df_skhynix['date'].astype('str')
df_skhynix['date'] = pd.to_datetime(df_skhynix['date'])

df_samsung = df_samsung[df_samsung['date'] > '2020-01-01']

df_samsung_filter = df_samsung[['date', 'close', 'diffratio']].rename(columns={'close': 'samsung_close', 'diffratio': 'samsung_diffratio'})
df_skhynix_filter = df_skhynix[['date', 'close', 'diffratio']].rename(columns={'close': 'skhynix_close', 'diffratio': 'skhynix_diffratio'})

# merge two stocks
df = pd.merge(df_samsung_filter, df_skhynix_filter, on='date', how='left')

df.set_index('date', inplace=True)

In [9]:
df

            samsung_close  samsung_diffratio  skhynix_close  skhynix_diffratio
date
2020-01-02          55200          -0.010753          94700           0.006376
2020-01-03          55500           0.005435          94500          -0.002112
2020-01-06          55500           0.000000          94300          -0.002116
2020-01-07          55800           0.005405          94000          -0.003181
2020-01-08          56800           0.017921          97400           0.036170
...                   ...                ...            ...                ...
2023-12-21          75000           0.002674         140500           0.000000
2023-12-22          75900           0.012000         140600           0.000712
2023-12-26          76600           0.009223         140900           0.002134
2023-12-27          78000           0.018277         140400          -0.003549
2023-12-28          78500           0.006410         141500           0.007835

[985 rows x 4 columns]

In [31]:

# 주식 티커 및 거래 예산 설정
tickers = ['samsung', 'skhynix']
budget = 100000000  # 거래 예산 100,000,000원

# 거래 수수료 및 거래세 설정
transaction_fee_rate = 0.00015  # 0.015%
transaction_tax_rate = 0.002     # 0.2%

# 종가 데이터 가져오기
close_prices = df[[f'{ticker}_close' for ticker in tickers]].iloc[0]

# 최대 거래 가능한 주식 수 계산
max_shares = {}
for ticker in tickers:
    max_shares[ticker] = budget * 0.5 // close_prices[f'{ticker}_close']  # 소수점 없이 최대 주식 수 계산

# 각 주식의 수익률 계산
daily_returns = df[[f'{ticker}_close' for ticker in tickers]].pct_change().dropna()

# 포트폴리오 수익률 계산 (동일 비율로 투자)
weights = np.array([max_shares['samsung'], max_shares['skhynix']])  # 각 주식의 최대 주식 수
total_investment = sum(weights * close_prices)

# 거래 수수료 및 거래세 계산
total_transaction_fee = total_investment * transaction_fee_rate
total_transaction_tax = total_investment * transaction_tax_rate
net_investment = total_investment - (total_transaction_fee + total_transaction_tax)

# 포트폴리오 수익률 계산 (순 투자를 기준으로)
portfolio_returns = (daily_returns.dot(weights)) / net_investment

# 샤프 지수 계산
risk_free_rate = 0.03 / 252  # 연간 무위험 수익률을 일일로 변환 (예: 3%)
mean_return = portfolio_returns.mean()
std_dev = portfolio_returns.std()

# 샤프 지수 계산
sharpe_ratio = (mean_return - risk_free_rate) / std_dev

# 결과 출력
print(f"{tickers[0]}의 최대 거래 가능한 주식 수: {max_shares['samsung']}주")
print(f"{tickers[1]}의 최대 거래 가능한 주식 수: {max_shares['skhynix']}주")
print(f"포트폴리오의 샤프 지수: {sharpe_ratio:.4f}")

print(f"포트폴리오 PV: {max_shares['samsung'] * 78500 + max_shares['skhynix'] * 141500}")

samsung의 최대 거래 가능한 주식 수: 636.0주
skhynix의 최대 거래 가능한 주식 수: 353.0주
포트폴리오의 샤프 지수: -703.8817
포트폴리오 PV: 99875500.0

In [41]:
import numpy as np
import pandas as pd

# 데이터프레임 예시 (실제 데이터로 교체해야 합니다)

# df.set_index('date', inplace=True)

# 주식 티커 및 거래 예산 설정
tickers = ['samsung', 'skhynix']
budget = 100000000  # 거래 예산 100,000,000원

# 거래 수수료 및 거래세 설정
transaction_fee_rate = 0.00015  # 0.015%
transaction_tax_rate = 0.002     # 0.2%

# 종가 데이터 가져오기
close_prices = df[[f'{ticker}_close' for ticker in tickers]].iloc[0]

# 최대 거래 가능한 주식 수 계산
max_shares = {}
for ticker in tickers:
    max_shares[ticker] = budget * 0.5 // close_prices[f'{ticker}_close']  # 소수점 없이 최대 주식 수 계산

# 각 주식의 수익률 계산
daily_returns = df[[f'{ticker}_close' for ticker in tickers]].pct_change().dropna()

# 포트폴리오 투자 금액 계산
investment_per_stock = budget * 0.5  # 각 주식에 동일 비율로 투자
total_investment = 0
for ticker in tickers:
    shares = max_shares[ticker]
    investment = shares * close_prices[f'{ticker}_close']
    total_investment += investment

# 거래 수수료 및 거래세 계산
total_transaction_fee = total_investment * transaction_fee_rate
total_transaction_tax = total_investment * transaction_tax_rate
net_investment = total_investment - (total_transaction_fee + total_transaction_tax)

# 포트폴리오 수익률 계산 (순 투자를 기준으로)
weights = np.array([max_shares['samsung'], max_shares['skhynix']])  # 각 주식의 최대 주식 수
portfolio_returns = (daily_returns.dot(weights)) / net_investment

# 샤프 지수 계산 
risk_free_rate = 0.03 / 252  # 연간 무위험 수익률을 일일로 변환 (예: 3%)
mean_return = portfolio_returns.mean()
std_dev = portfolio_returns.std()

# 샤프 지수 계산
sharpe_ratio = (mean_return - risk_free_rate) / std_dev

# 결과 출력
print(f"{tickers[0]}의 최대 거래 가능한 주식 수: {max_shares['samsung']}주")
print(f"{tickers[1]}의 최대 거래 가능한 주식 수: {max_shares['skhynix']}주")
print(f"포트폴리오의 샤프 지수: {sharpe_ratio:.4f}")

print(f"포트폴리오 PV: {max_shares['samsung'] * 78500 + max_shares['skhynix'] * 141500}")

samsung의 최대 거래 가능한 주식 수: 905.0주
skhynix의 최대 거래 가능한 주식 수: 527.0주
포트폴리오의 샤프 지수: -484.1920
포트폴리오 PV: 145613000.0