In [3]:
# 필요한 라이브러리 임포트
import pandas as pd

# CSV 파일 읽기
file_path = '000660_SK하이닉스_20150101_20240828.csv'  # 원본 CSV 파일 경로
data = pd.read_csv(file_path)

# 필요한 컬럼 리스트
columns_to_extract = [
    'date', 'open', 'high', 'low', 'close', 'volume', 
    'per', 'pbr', 'roe', 'open_lastclose_ratio', 
    'high_close_ratio', 'low_close_ratio', 'diffratio', 
    'volume_lastvolume_ratio', 'close_ma5_ratio', 
    'volume_ma5_ratio', 'close_ma10_ratio', 
    'volume_ma10_ratio', 'close_ma20_ratio', 
    'volume_ma20_ratio', 'close_ma60_ratio', 
    'volume_ma60_ratio', 'close_ma120_ratio', 
    'volume_ma120_ratio', 'ind', 'ind_diff', 
    'ind_ma5', 'ind_ma10', 'ind_ma20', 
    'ind_ma60', 'ind_ma120', 'inst', 
    'inst_diff', 'inst_ma5', 'inst_ma10', 
    'inst_ma20', 'inst_ma60', 'inst_ma120', 
    'foreign', 'foreign_diff', 
    'foreign_ma5', 'foreign_ma10', 
    'foreign_ma20', 'foreign_ma60', 
    'foreign_ma120'
]

# 필요한 컬럼만 추출
extracted_data = data[columns_to_extract]

# 새로운 CSV 파일로 저장
output_file_path = '000660_SK하이닉스.csv'  # 저장할 CSV 파일 경로
extracted_data.to_csv(output_file_path, index=False)

extracted_data

,date,open,high,low,close,volume,per,pbr,roe,open_lastclose_ratio,...,inst_ma20,inst_ma60,inst_ma120,foreign,foreign_diff,foreign_ma5,foreign_ma10,foreign_ma20,foreign_ma60,foreign_ma120
0,20150102,47950,48400,47650,47750,1155944,6.44,0.89,15.63,0.004188,...,0.010585,0.015523,NaN,-0.040114,0.022567,0.075202,0.044355,0.044693,0.084455,NaN
1,20150105,48050,48400,47500,47650,1409146,6.44,0.89,15.63,0.006283,...,-0.003765,0.008442,NaN,0.155758,0.195872,0.069776,0.066663,0.049272,0.090068,NaN
2,20150106,47000,47600,46900,47500,1661196,6.44,0.89,15.63,-0.013641,...,-0.014924,0.007370,NaN,-0.024819,-0.180577,0.059155,0.033934,0.039109,0.091006,NaN
3,20150107,46700,47600,46700,47400,1821266,6.44,0.89,15.63,-0.016842,...,-0.009139,0.006743,NaN,-0.067303,-0.042484,-0.007831,0.009276,0.027652,0.093636,NaN
4,20150108,48250,50000,47900,49950,5006675,6.44,0.89,15.63,0.017932,...,-0.003374,0.004169,NaN,0.281405,0.348707,0.060986,0.039500,0.030326,0.101771,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,20240821,193000,195400,191100,192600,4508983,5.03,1.04,24.26,-0.033550,...,-0.013317,-0.030585,-0.026244,-0.155469,-0.339691,0.066220,0.073073,0.006192,0.014404,0.021693
2370,20240822,192000,194400,189000,191100,3166217,5.03,1.04,24.26,-0.003115,...,-0.017804,-0.030067,-0.026518,0.026600,0.182069,0.062359,0.075820,0.006412,0.014117,0.022316
2371,20240823,186000,189300,185400,185500,4371332,5.03,1.04,24.26,-0.026688,...,-0.015746,-0.027110,-0.024673,-0.309355,-0.335954,-0.056648,0.046271,0.005762,0.008729,0.018203
2372,20240826,187800,188500,179600,179600,4913204,5.03,1.04,24.26,0.012399,...,-0.019562,-0.024369,-0.023629,-0.228445,0.080909,-0.096490,0.004426,0.003036,0.005209,0.015678
2373,20240827,176800,180200,173400,175000,5741455,5.03,1.04,24.26,-0.015590,...,-0.014518,-0.024951,-0.022794,-0.223905,0.004541,-0.178115,-0.028216,-0.019067,0.004389,0.011805

In [5]:
# 필요한 라이브러리 임포트
import pandas as pd

# CSV 파일 읽기
file_path = '005380_현대차_20150101_20240828.csv'  # 원본 CSV 파일 경로
data = pd.read_csv(file_path)

# 필요한 컬럼 리스트
columns_to_extract = [
    'date', 'open', 'high', 'low', 'close', 'volume', 
    'per', 'pbr', 'roe', 'open_lastclose_ratio', 
    'high_close_ratio', 'low_close_ratio', 'diffratio', 
    'volume_lastvolume_ratio', 'close_ma5_ratio', 
    'volume_ma5_ratio', 'close_ma10_ratio', 
    'volume_ma10_ratio', 'close_ma20_ratio', 
    'volume_ma20_ratio', 'close_ma60_ratio', 
    'volume_ma60_ratio', 'close_ma120_ratio', 
    'volume_ma120_ratio', 'ind', 'ind_diff', 
    'ind_ma5', 'ind_ma10', 'ind_ma20', 
    'ind_ma60', 'ind_ma120', 'inst', 
    'inst_diff', 'inst_ma5', 'inst_ma10', 
    'inst_ma20', 'inst_ma60', 'inst_ma120', 
    'foreign', 'foreign_diff', 
    'foreign_ma5', 'foreign_ma10', 
    'foreign_ma20', 'foreign_ma60', 
    'foreign_ma120'
]

# 필요한 컬럼만 추출
extracted_data = data[columns_to_extract]

# 새로운 CSV 파일로 저장
output_file_path = '005380_현대자동차.csv'  # 저장할 CSV 파일 경로
extracted_data.to_csv(output_file_path, index=False)

extracted_data

,date,open,high,low,close,volume,per,pbr,roe,open_lastclose_ratio,...,inst_ma20,inst_ma60,inst_ma120,foreign,foreign_diff,foreign_ma5,foreign_ma10,foreign_ma20,foreign_ma60,foreign_ma120
0,20150102,169000,170500,167000,169000,458014,7.93,0.64,8.93,0.000000,...,0.067033,0.005071,NaN,-0.067679,0.049495,-0.133927,-0.181062,-0.165715,-0.063456,NaN
1,20150105,171000,171000,166000,168000,454073,7.93,0.64,8.93,0.011834,...,0.058028,0.003052,NaN,-0.178337,-0.110658,-0.151413,-0.167663,-0.169910,-0.060716,NaN
2,20150106,166500,167000,164000,164500,635059,7.93,0.64,8.93,-0.008929,...,0.030578,0.001799,NaN,-0.108524,0.069813,-0.141999,-0.155015,-0.177485,-0.062169,NaN
3,20150107,163000,171500,163000,170000,511006,7.93,0.64,8.93,-0.009119,...,0.011407,-0.000741,NaN,0.148106,0.256630,-0.064722,-0.124183,-0.173039,-0.059551,NaN
4,20150108,172500,178000,171000,178000,902742,7.93,0.64,8.93,0.014706,...,0.008165,-0.006189,NaN,0.325908,0.177802,0.023895,-0.065889,-0.160172,-0.051815,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,20240821,257500,257500,251000,252500,359513,4.76,0.53,12.01,0.005859,...,-0.044498,-0.027936,-0.023962,-0.127347,-0.332198,0.143229,0.099427,0.021466,0.011710,0.055932
2370,20240822,253500,254000,245500,248000,497250,4.76,0.53,12.01,0.003960,...,-0.053270,-0.033207,-0.026109,-0.085866,0.041481,0.132648,0.091883,0.028650,0.012213,0.054458
2371,20240823,245500,254000,245000,252500,449189,4.76,0.53,12.01,-0.010081,...,-0.043888,-0.029748,-0.025375,0.043478,0.129345,0.051971,0.081020,0.040315,0.015069,0.054142
2372,20240826,255500,258000,247500,249500,469538,4.76,0.53,12.01,0.011881,...,-0.046524,-0.028948,-0.026566,-0.073306,-0.116784,-0.007638,0.061923,0.043604,0.013206,0.053118
2373,20240827,248500,251000,244500,247500,546990,4.76,0.53,12.01,-0.004008,...,-0.060253,-0.033943,-0.028144,-0.002959,0.070347,-0.049200,0.072233,0.038701,0.017796,0.051151

In [7]:
# 필요한 라이브러리 임포트
import pandas as pd

# CSV 파일 읽기
file_path = '035720_카카오_20150101_20240828.csv'  # 원본 CSV 파일 경로
data = pd.read_csv(file_path)

# 필요한 컬럼 리스트
columns_to_extract = [
    'date', 'open', 'high', 'low', 'close', 'volume', 
    'per', 'pbr', 'roe', 'open_lastclose_ratio', 
    'high_close_ratio', 'low_close_ratio', 'diffratio', 
    'volume_lastvolume_ratio', 'close_ma5_ratio', 
    'volume_ma5_ratio', 'close_ma10_ratio', 
    'volume_ma10_ratio', 'close_ma20_ratio', 
    'volume_ma20_ratio', 'close_ma60_ratio', 
    'volume_ma60_ratio', 'close_ma120_ratio', 
    'volume_ma120_ratio', 'ind', 'ind_diff', 
    'ind_ma5', 'ind_ma10', 'ind_ma20', 
    'ind_ma60', 'ind_ma120', 'inst', 
    'inst_diff', 'inst_ma5', 'inst_ma10', 
    'inst_ma20', 'inst_ma60', 'inst_ma120', 
    'foreign', 'foreign_diff', 
    'foreign_ma5', 'foreign_ma10', 
    'foreign_ma20', 'foreign_ma60', 
    'foreign_ma120'
]

# 필요한 컬럼만 추출
extracted_data = data[columns_to_extract]

# 새로운 CSV 파일로 저장
output_file_path = '035720_카카오.csv'  # 저장할 CSV 파일 경로
extracted_data.to_csv(output_file_path, index=False)

extracted_data

,date,open,high,low,close,volume,per,pbr,roe,open_lastclose_ratio,...,inst_ma20,inst_ma60,inst_ma120,foreign,foreign_diff,foreign_ma5,foreign_ma10,foreign_ma20,foreign_ma60,foreign_ma120
0,20150102,24880,27740,24860,27440,5814505,50.89,6.83,14.81,-0.798706,...,0.033264,0.026334,NaN,0.012534,0.242916,-0.090256,-0.062313,-0.021560,0.017548,NaN
1,20150105,28100,29160,27920,28900,6872685,50.89,6.83,14.81,0.024052,...,0.038767,0.028014,NaN,0.040937,0.028403,-0.064074,-0.053191,-0.021733,0.018722,NaN
2,20150106,28860,29860,28500,29060,5229540,50.89,6.83,14.81,-0.001384,...,0.047991,0.030565,NaN,-0.065206,-0.106144,-0.087670,-0.060351,-0.027859,0.017987,NaN
3,20150107,28800,29860,28560,29640,4295315,50.89,6.83,14.81,-0.008947,...,0.067176,0.035594,NaN,-0.005039,0.060167,-0.049431,-0.067097,-0.031911,0.017941,NaN
4,20150108,29980,30300,29300,29460,3656030,50.89,6.83,14.81,0.011471,...,0.070241,0.037111,NaN,0.133650,0.138690,0.023375,-0.050237,-0.026012,0.020558,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,20240821,36500,36800,36400,36600,669506,26.58,1.49,5.83,0.000000,...,-0.065394,-0.045458,-0.037436,0.238600,0.371651,0.079618,0.005496,0.036867,-0.028685,-0.041075
2370,20240822,36900,37700,36750,37550,1653724,26.58,1.49,5.83,0.008197,...,-0.055299,-0.040274,-0.036109,0.151552,-0.087047,0.060940,0.028427,0.034527,-0.022840,-0.040638
2371,20240823,37450,37800,37100,37450,872362,26.58,1.49,5.83,-0.002663,...,-0.056285,-0.036709,-0.033418,-0.131828,-0.283381,0.050504,0.027191,0.020942,-0.020198,-0.040910
2372,20240826,37550,38900,37150,38700,1753855,26.58,1.49,5.83,0.002670,...,-0.038406,-0.030414,-0.030847,0.106098,0.237926,0.046274,0.065971,0.033675,-0.018389,-0.038185
2373,20240827,38650,38900,38000,38000,1142253,26.58,1.49,5.83,-0.001292,...,-0.024349,-0.029407,-0.029541,-0.324054,-0.430152,0.008073,0.021150,0.011774,-0.020424,-0.040686